
name: CI

on:
  push:
    branches: main
  pull_request:
  workflow_call:  # allow this workflow to be called from other workflows

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v7
        with:
          extraFiles: deder.pkl
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Install deder
        run: brew install sake92/tap/deder
      - name: Compile
        run: deder exec -t compile
      - name: Test
        run: deder exec -t test
  compile-scala-cli-examples:
    runs-on: ubuntu-latest
    continue-on-error: true # not critical
    steps:
      - uses: actions/checkout@v5
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: temurin:21
      - name: Compile Scala CLI examples
        run: |
          ./scripts/compile-scala-cli-examples.sh examples/scala-cli
          ./scripts/compile-scala-cli-examples.sh examples/htmx
